VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('05')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('47')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202401051147
version_date = '2024/01/05 11:47'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
