VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('06')
VERSION_HOUR = int('07')
VERSION_MINUTE = int('38')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202401060738
version_date = '2024/01/06 07:38'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
