VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('07')
VERSION_HOUR = int('17')
VERSION_MINUTE = int('05')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202401071705
version_date = '2024/01/07 17:05'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
