VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('11')
VERSION_HOUR = int('17')
VERSION_MINUTE = int('49')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202401111749
version_date = '2024/01/11 17:49'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
